### PR TITLE
New touch screen based virtual keyboard.

### PR DESCRIPTION
**Pull request by paulguy**
I've merged the two input drivers together due to their overlaps in functionality and in this case, made it easier for me, though in retrospect maybe they could've been kept separate since there is no mode switching anymore.

Anyway, this makes the shell considerably more usable.

### CODE REVIEW

**Comment by paulguy** [comment]
Reworked the whole thing.  It's cleaner now, and the two unrelated files are now separate.

**Comment by xerpi** [comment]
Looks pretty good, do you want me to merge it or do you plan to do more commits?

**Comment by paulguy** [comment]
As far as features goes, I think it's pretty complete.  Bugs might crop up though, I guess.  If you want to merge it in you can.  Should I add myself to the copyright notices?  I'm really unsure how that all works.

**Comment by xerpi** [comment]
Yeah feel free to add yourself to the copyright.

**Comment by paulguy** [comment]
Alrighty.

**Comment by xerpi** [comment]
Hey, I think you missed to add arch/arm/mach-nintendo3ds/include/mach/bottom_lcd.h and the .c when submitting this PR.

**Comment by paulguy** [comment]
Oh jeez yeah I notice that.  I have no idea what happened since that was months ago.  I assume it's just me being bad at Git but they're missing here too.  I've tried applying the changes I think I made based on what the functions are calling from that file, but now it's just crashing before bringing up a console (just displaying the white sort of splash screen with the random colored top screen) and I have no idea how to debug this.  Last time I got lucky and it more or less just worked without much drama.  I'll try to look over all my code to see if there are any problems but I can't give you any promises.  Sorry.

EDIT: Transferring it by putting the SD card in my reader rather than using ftpd seems to have fixed the crashing (maybe some binary/ascii mode nonsense going on) but there's still another issue that i still need to look in to.

EDIT 2:  I fixed it and cleaned up the commits.  No idea how to get it to do a thing because this pull request doesn't track the changes anymore, but they're in my original branch.

**Pull request merged**
