### PR TITLE
added untested sdmmc write and size support

### PR DESCRIPTION
**Pull request by DarkKirb**

### CODE REVIEW

**Comment by ParzivalWolfram** [comment]
I'm gonna test this pull request.

**Comment by DarkKirb** [comment]
It doesn't work that well yet, it freezes when you try to mount an ext partition rw and sometimes when you start it too

**Comment by ParzivalWolfram** [comment]
Any chance you could fix it? I'm really stupidly close to getting gcc and
make running, among a few other useful things. They'd be pointless without
R/W SD access, though.

**Comment by xerpi** [comment]
Thanks for the patch!

The Linux port will be continued by @Wolfvak here: https://github.com/Wolfvak/linux-3ds

**Pull request closed without merging**
